version: 0.0
os: linux
files:
  - source: s3://scenery-bucket/s3_ok/
    destination: /opt/demo  # Use absolute path

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

