version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"
      - apt-get update && apt-get install -y git

  pre_build:
    commands:
      - echo "Cloning Community repo..."
      - git clone https://github.com/madhukamath29/demo-odoo17.git community-repo

      - echo "Cloning Enterprise repo..."
      - git clone https://github.com/madhukamath29/Enterprise-odoo-repo.git enterprise-repo

      - echo "Cloning Third-party addons from Inv-repo..."
      - git clone --branch Third-party-addon https://github.com/madhukamath29/INV-Repo.git third-party-repo

      - echo "Cloning Common addons from Inv-repo..."
      - git clone --branch common-addon https://github.com/madhukamath29/INV-Repo.git common-addon-repo

      - echo "Cloning GST branch from Inv-repo..."
      - git clone --branch GST-Enterprise --single-branch https://github.com/madhukamath29/INV-Repo.git gst-repo

  build:
    commands:
      - echo "Merging necessary repositories into community repo..."
      - cp -r enterprise-repo/* community-repo/
      - cp -r third-party-repo/* community-repo/
      - cp -r common-addon-repo/* community-repo/
      - cp -r gst-repo/* community-repo/
      - echo "Files merged into community repo..."

  post_build:
    commands:
     - echo "Build complete, files merged...."
artifacts:
  files:
    - '**/*'  # Upload all merged files

  base-directory: community-repo  # The community repo now contains all merged files
