version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Cloning repositories...
      - git clone https://github.com/madhukamath29/enterprise_repo.git 
      - git clone https://github.com/madhukamath29/test-pipeline.git
  build:
    commands:
      - echo Merging code from both repositories...
      - mkdir merged_code
      - cp -r enterprise_repo/* merged_code/
      - cp -r test-pipeline/* merged_code/
      - echo Merged code successfully.

  post_build:
    commands:
      - echo Preparing artifacts for deployment...
      - mkdir -p temp/test   # Use relative path here
      - cp -r merged_code/* temp/test/  # Use relative path here
      - ls -l temp
      - ls -l temp/test/
      - echo Artifacts ready....

artifacts:
  files:
    - 'temp/test/**/*'  # Match all files and directories in temp/test relative to the build root
  discard-paths: no
