version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Cloning repositories...
      - git clone https://github.com/madhukamath29/enterprise_repo.git /home/enterprise
      - git clone https://github.com/madhukamath29/test-pipeline.git /home/test-pipeline

  build:
    commands:
      - echo Merging code from both repositories...
      - mkdir merged_code
      - cp -r /home/enterprise/* merged_code/
      - ls -l merged_code/
      - cp -r /home/test-pipeline/* merged_code/
      - ls -l merged_code/
      - echo Merged code successfully...

  post_build:
    commands:
      - echo Preparing artifacts for deployment.....
      - mkdir -p temp/test
      - cp -r merged_code/* temp/test/
      - ls -l temp
      - ls -l temp/test/
      - echo Artifacts ready.......

artifacts:
  files:
    - 'temp1/test/**/*'
